export const users = [
	{
		userDetails: {
			name: "Jack The dog",
			countryCode: "DE",
			postCode: 55128,
			country: "Germany",
			city: "Mainz",
			street: "Ackermannweg",
			streetNumber: "10",
		},
		code: "1111",
		phoneNumber: "+78005553535",
	},
	{
		userDetails: {
			name: "Lisa Maier",
			countryCode: "DE",
			postCode: 70192,
			country: "Germany",
			city: "Stuttgart",
			street: "Lenbachstraße",
			streetNumber: "2-26",
		},
		code: "9204",
		phoneNumber: "+49177178780",
	},
	{
		userDetails: {
			name: "Thomas Müller",
			countryCode: "AT",
			postCode: 5020,
			country: "Austria",
			city: "Salzburg",
			street: "Eniglstraße",
			streetNumber: "7",
		},
		code: "7166",
		phoneNumber: "+4989587083665",
	},
	{
		userDetails: {
			name: "Dagmar Koller",
			countryCode: "DE",
			postCode: 60486,
			country: "Germany",
			city: "Frankfurt am Main",
			street: "Ackermannweg",
			streetNumber: 8,
		},
		code: "3310",
		phoneNumber: "+49152010183330",
	},
	{
		userDetails: {
			name: "Frank Rosin",
			countryCode: "DE",
			postCode: 4058,
			country: "Germany",
			city: "Basel",
			street: "Mattenstrasse",
			streetNumber: "24a",
		},
		code: "1606",
		phoneNumber: "+4930408173216",
	},
	{
		userDetails: {
			name: "Sara Herring",
			countryCode: "DE",
			postCode: 79576,
			country: "Germany",
			city: "Weil am Rhein",
			street: "Colmarer Str.",
			streetNumber: "6",
		},
		code: "9204",
		phoneNumber: "+4917634312574",
	},
];
